- name: "Verify audit on hosts"
  hosts: db
  user: root

  vars_files:
    - conf/env_vars.yml

  tasks:

  - name: Test var
    include: "play/listdbdirectory.yml"
    become_user: '{{instanceuser}}'
    become: true
    become_method: su
    become_flags: "-"

  - name:
    debug: 
      var: dblist

  - name: loop
    shell: 'echo "{{item}}"'
    with_items: "{{dblist.stdout_lines}}"

