# ------------------------------------
# Execute script on Audit master node
# -------------------------------------

- name: "Verify audit on hosts"
  hosts: db

  vars_files:
    - conf/env_vars.yml

  tasks:

  - fail: msg="auditdir variable not defined"
    when: auditdir is not defined

  - name: Verify audit policy for every databases
    include: play/tools/runscriptfordatabases.yml
    vars: 
      include_script: ../verify/db2verifyauditpolicies.yml
