# ------------------------------------
# Execute script on Audit master node
# -------------------------------------

- name: "Collect audit logs"
  hosts: db

  vars_files:
    - conf/env_vars.yml

  tasks:

  - fail: msg="auditdir variable not defined"
    when: auditdir is not defined

  - name: Archive and collect log data for every database
    include: play/tools/runscriptfordatabases.yml
    vars: 
      include_script: ../collect/auditarchive.yml

    
