- name: "Verify audit on hosts"
  hosts: db

  vars_files:
    - conf/env_vars.yml
    - conf/env_db.yml

  vars:
    dblist: '{{dbset}}'

  tasks:

  - fail: msg="auditdir variable not defined"
    when: auditdir is not defined

  - include: play/runremotescript.yml
    vars:
      db2include: db2verifyauditpolicies.yml
      ignoredb2errors : false
      db2auditbecome: false
    name: "Configure audit policy in databases"
    with_list: '{{ dblist }}'
