- name: "Create db2audit user"
  hosts: db
  user: root

  vars_files:
    - conf/env_vars.yml
    - conf/env_db.yml

  vars:
    dblist: '{{dbset}}'

  tasks:

  - include: play/createaudituser.yml

  - include: play/createauditpolicy.yml
    become_user: '{{instanceuser}}'
    become: true
    become_method: su
    become_flags: "-"

  - include: play/grantaudituser.yml
    name: "Elevate {{ audituser}} in databases "
    with_list: '{{ dblist }}'

  - include: play/runremotescript.yml
    vars:
      db2include: db2createauditpolicy.yml
      ignoredb2errors : true
    name: "Configure audit policy in databases"
    with_list: '{{ dblist }}'
