# ----------------------------------
# Execute script on Privilege node
# ----------------------------------

- name: "Create db2audit user"
  hosts: db
  user: root

  vars_files:
    - conf/env_vars.yml

  tasks:

  - include: play/grantaudit/createaudituser.yml

  - include: play/grantaudit/createauditpolicy.yml
    become_user: '{{instanceuser}}'
    become: true
    become_method: su
    become_flags: "-"

  - name: Grant SECADM authority to {{audituser}} for every database
    include: play/tools/runscriptfordatabases.yml
    vars: 
      include_script: ../grantaudit/grantaudit.yml
    become_user: '{{instanceuser}}'
    become: true
    become_method: su
    become_flags: "-"

  - name: Create audit policy for every database
    include: play/tools/runscriptfordatabases.yml
    vars: 
      include_script: ../grantaudit/auditpolicy.yml
    become_user: '{{audituser}}'
    become: true
    become_method: su
    become_flags: "-"




