- name: "Create db2audit user"
  hosts: all
  user: root

  vars_files:
    - conf/env_vars.yml
    - conf/env_db.yml

  tasks:

  - include: play/createaudituser.yml

  - include: play/createauditpolicy.yml
    become_user: '{{instanceuser}}'
    become: true
    become_method: su
    become_flags: "-"

  - include: play/grantaudituser.yml
    name: "Elevate {{ audituser}} in databases "
    with_list: '{{ databases }}'

  - include: play/setupauditpolicy.yml
    name: "Configure audit policy in databases"
    with_list: '{{ databases }}'
