- name: Create temporary file to run a script
  become_user: '{{instanceuser}}'
  become: true
  become_method: su
  become_flags: "-"

  ansible.builtin.tempfile:
    state: file
    suffix: temp
  register: temp_file

- name: Create DB2 script file {{ temp_file }}
  copy:
    dest: '{{ temp_file.path }}'
    content: |
      connect to {{item}};
      grant SECADM on database to user {{ audituser}};
      terminate;

- name: Execute the script
  shell: 'db2 -tvf {{ temp_file.path }}'
  become_user: '{{instanceuser}}'
  become: true
  become_method: su
  become_flags: "-"

- name: Remove temporary fule
  ansible.builtin.file:
    path: '{{ temp_file.path }}'
    state: absent
