- name: Create temporary file to run a script
  become_user: '{{audituser}}'
  become: '{{db2auditbecome}}'
  become_method: su
  become_flags: "-"

  ansible.builtin.tempfile:
    state: file
    suffix: temp
  register: temp_file

- include: '{{db2include}}'

- name: Execute the script
  shell: 'db2 -tvf {{ temp_file.path }}'
  become_user: '{{audituser}}'
  become: '{{db2auditbecome}}'
  become_method: su
  become_flags: "-"
  ignore_errors: '{{ignoredb2errors}}'
  register: output


- name: Remove temporary fule
  ansible.builtin.file:
    path: '{{ temp_file.path }}'
    state: absent

