- name: Create temporary file to run a script
  become_user: '{{audituser}}'
  become: true
  become_method: su
  become_flags: "-"

  ansible.builtin.tempfile:
    state: file
    suffix: temp
  register: temp_file

- name: Create DB2 script file {{ temp_file }}
  copy:
    dest: '{{ temp_file.path }}'
    content: |
      connect to {{item}};
      create audit policy {{auditpolicyname}} {{auditpolicyspec}} ERROR TYPE NORMAL;
      AUDIT database USING POLICY {{auditpolicyname}};
      terminate;

- name: Execute the script
  shell: 'db2 -tvf {{ temp_file.path }}'
  become_user: '{{audituser}}'
  become: true
  become_method: su
  become_flags: "-"
  ignore_errors: True
  register: output

- name: Remove temporary fule
  ansible.builtin.file:
    path: '{{ temp_file.path }}'
    state: absent

